variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_TAG: $DOCKER_REGISTRY:$CI_COMMIT_SHA
  CLAIR_OUTPUT: High

image: docker:latest

stages:
  - testing
  - building
  - deployment

linting:
  image: node:latest
  tags:
    - docker
  stage: testing
  before_script:
    - npm init --yes
    - npm install -g eslint
  script:
    - eslint -c .eslintrc.js server.js

docker-build:
  image: docker:latest
  stage: building
  tags:
    - docker
  services:
    - docker:dind
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - echo $DOCKER_REGISTRY
    - echo $IMAGE_TAG
    - $REGISTRY_PASSWORD | docker login --username $REGISTRY_USERNAME --password-stdin $DOCKER_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deployment:
  stage: deployment
  image: alpine/k8s:1.16.15
  tags:
    - docker
  before_script:
    - kubectl version
    - kubectl config view
  script:
    - kubectl set image deployment/front-end front-end=$IMAGE_TAG -n sock-shop
  when: manual
