variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_TAG: $DOCKER_REGISTRY:$CI_COMMIT_SHA
  CLAIR_OUTPUT: High

image: docker:latest

stages:
  - linting
  - testing
  - building
  - deployment

eslint:
  image: node:latest
  tags:
    - docker
  stage: linting
  before_script:
    - npm init --yes
    - npm install -g eslint
  script:
    - eslint -c .eslintrc.js server.js

security_scan:
  stage: testing
  tags:
    - docker
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  services:
    - docker:dind
  script:
    - trivy --no-progress --output scanning-report.txt  $IMAGE_TAG
    #- trivy --exit-code 1 --no-progress --severity CRITICAL $IMAGE_TAG
  artifacts:
    reports:
      container_scanning: scanning-report.txt

testing-login:
  image: docker:latest
  stage: testing
  tags:
    - docker
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $DOCKER_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker run -d --name testcontainer -p 8079:8079 $IMAGE_TAG
    - curl -I localhost:8079  2>/dev/null | head -n 1 | cut -d$' ' -f2

docker-build:
  image: docker:latest
  stage: building
  tags:
    - docker
  services:
    - docker:dind
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $DOCKER_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deployment:
  stage: deployment
  image: alpine/k8s:1.16.15
  tags:
    - docker
  before_script:
    - aws eks update-kubeconfig --name app-first-sec
    - kubectl version
  script:
    - kubectl set image deployment/front-end front-end=$IMAGE_TAG -n sock-shop
  when: manual
